/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/about'
      | '/dashboard/account'
      | '/dashboard/agents'
      | '/dashboard/app'
      | '/dashboard/app-panel'
      | '/dashboard/app-panel/[id]'
      | '/dashboard/app-panel/list'
      | '/dashboard/app/[extensionRoute]'
      | '/dashboard/app/docker'
      | '/dashboard/app/files'
      | '/dashboard/app/firewall'
      | '/dashboard/app/process'
      | '/dashboard/batch-exec'
      | '/dashboard/cost'
      | '/dashboard/cron'
      | '/dashboard/cron-history/[cronName]'
      | '/dashboard/exec'
      | '/dashboard/js-runtime'
      | '/dashboard/kv'
      | '/dashboard/loadbalance'
      | '/dashboard/logs'
      | '/dashboard/map'
      | '/dashboard/node-manage'
      | '/dashboard/node/[uuid]'
      | '/dashboard/node/[uuid]/LatencyView'
      | '/dashboard/node/[uuid]/[extensionRoute]'
      | '/dashboard/node/[uuid]/docker'
      | '/dashboard/node/[uuid]/files'
      | '/dashboard/node/[uuid]/firewall'
      | '/dashboard/node/[uuid]/latency'
      | '/dashboard/node/[uuid]/ping'
      | '/dashboard/node/[uuid]/process'
      | '/dashboard/node/[uuid]/setting'
      | '/dashboard/node/[uuid]/status'
      | '/dashboard/node/[uuid]/traffic'
      | '/dashboard/node/[uuid]/update'
      | '/dashboard/node/[uuid]/webshell'
      | '/dashboard/overview'
      | '/dashboard/scripts'
      | '/dashboard/servers'
      | '/dashboard/servers-detail/[backendId]'
      | '/dashboard/sessions'
      | '/dashboard/settings'
      | '/dashboard/settings/general'
      | '/dashboard/settings/login'
      | '/dashboard/settings/notification'
      | '/dashboard/settings/site'
      | '/dashboard/token'
      | '/dashboard/tokenCeate'
      | '/dashboard/tokenDetail'
      | '/dashboard/tokenEdit'
      | '/dashboard/tokenImport'
    >,
    '/dashboard/about': RouteRecordInfo<
      '/dashboard/about',
      '/dashboard/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/account': RouteRecordInfo<
      '/dashboard/account',
      '/dashboard/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/agents': RouteRecordInfo<
      '/dashboard/agents',
      '/dashboard/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/app': RouteRecordInfo<
      '/dashboard/app',
      '/dashboard/app',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/app/[extensionRoute]'
      | '/dashboard/app/docker'
      | '/dashboard/app/files'
      | '/dashboard/app/firewall'
      | '/dashboard/app/process'
    >,
    '/dashboard/app/[extensionRoute]': RouteRecordInfo<
      '/dashboard/app/[extensionRoute]',
      '/dashboard/app/:extensionRoute',
      { extensionRoute: ParamValue<true> },
      { extensionRoute: ParamValue<false> },
      | never
    >,
    '/dashboard/app/docker': RouteRecordInfo<
      '/dashboard/app/docker',
      '/dashboard/app/docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/app/files': RouteRecordInfo<
      '/dashboard/app/files',
      '/dashboard/app/files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/app/firewall': RouteRecordInfo<
      '/dashboard/app/firewall',
      '/dashboard/app/firewall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/app/process': RouteRecordInfo<
      '/dashboard/app/process',
      '/dashboard/app/process',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/app-panel': RouteRecordInfo<
      '/dashboard/app-panel',
      '/dashboard/app-panel',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/app-panel/[id]'
      | '/dashboard/app-panel/list'
    >,
    '/dashboard/app-panel/[id]': RouteRecordInfo<
      '/dashboard/app-panel/[id]',
      '/dashboard/app-panel/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/app-panel/list': RouteRecordInfo<
      '/dashboard/app-panel/list',
      '/dashboard/app-panel/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/batch-exec': RouteRecordInfo<
      '/dashboard/batch-exec',
      '/dashboard/batch-exec',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/cost': RouteRecordInfo<
      '/dashboard/cost',
      '/dashboard/cost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/cron': RouteRecordInfo<
      '/dashboard/cron',
      '/dashboard/cron',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/cron-history/[cronName]': RouteRecordInfo<
      '/dashboard/cron-history/[cronName]',
      '/dashboard/cron-history/:cronName',
      { cronName: ParamValue<true> },
      { cronName: ParamValue<false> },
      | never
    >,
    '/dashboard/exec': RouteRecordInfo<
      '/dashboard/exec',
      '/dashboard/exec',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/js-runtime': RouteRecordInfo<
      '/dashboard/js-runtime',
      '/dashboard/js-runtime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/kv': RouteRecordInfo<
      '/dashboard/kv',
      '/dashboard/kv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/loadbalance': RouteRecordInfo<
      '/dashboard/loadbalance',
      '/dashboard/loadbalance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/logs': RouteRecordInfo<
      '/dashboard/logs',
      '/dashboard/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/map': RouteRecordInfo<
      '/dashboard/map',
      '/dashboard/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/node/[uuid]': RouteRecordInfo<
      '/dashboard/node/[uuid]',
      '/dashboard/node/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | '/dashboard/node/[uuid]/LatencyView'
      | '/dashboard/node/[uuid]/[extensionRoute]'
      | '/dashboard/node/[uuid]/docker'
      | '/dashboard/node/[uuid]/files'
      | '/dashboard/node/[uuid]/firewall'
      | '/dashboard/node/[uuid]/latency'
      | '/dashboard/node/[uuid]/ping'
      | '/dashboard/node/[uuid]/process'
      | '/dashboard/node/[uuid]/setting'
      | '/dashboard/node/[uuid]/status'
      | '/dashboard/node/[uuid]/traffic'
      | '/dashboard/node/[uuid]/update'
      | '/dashboard/node/[uuid]/webshell'
    >,
    '/dashboard/node/[uuid]/[extensionRoute]': RouteRecordInfo<
      '/dashboard/node/[uuid]/[extensionRoute]',
      '/dashboard/node/:uuid/:extensionRoute',
      { uuid: ParamValue<true>, extensionRoute: ParamValue<true> },
      { uuid: ParamValue<false>, extensionRoute: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/docker': RouteRecordInfo<
      '/dashboard/node/[uuid]/docker',
      '/dashboard/node/:uuid/docker',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/files': RouteRecordInfo<
      '/dashboard/node/[uuid]/files',
      '/dashboard/node/:uuid/files',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/firewall': RouteRecordInfo<
      '/dashboard/node/[uuid]/firewall',
      '/dashboard/node/:uuid/firewall',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/latency': RouteRecordInfo<
      '/dashboard/node/[uuid]/latency',
      '/dashboard/node/:uuid/latency',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/LatencyView': RouteRecordInfo<
      '/dashboard/node/[uuid]/LatencyView',
      '/dashboard/node/:uuid/LatencyView',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/ping': RouteRecordInfo<
      '/dashboard/node/[uuid]/ping',
      '/dashboard/node/:uuid/ping',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/process': RouteRecordInfo<
      '/dashboard/node/[uuid]/process',
      '/dashboard/node/:uuid/process',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/setting': RouteRecordInfo<
      '/dashboard/node/[uuid]/setting',
      '/dashboard/node/:uuid/setting',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/status': RouteRecordInfo<
      '/dashboard/node/[uuid]/status',
      '/dashboard/node/:uuid/status',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/traffic': RouteRecordInfo<
      '/dashboard/node/[uuid]/traffic',
      '/dashboard/node/:uuid/traffic',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/update': RouteRecordInfo<
      '/dashboard/node/[uuid]/update',
      '/dashboard/node/:uuid/update',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node/[uuid]/webshell': RouteRecordInfo<
      '/dashboard/node/[uuid]/webshell',
      '/dashboard/node/:uuid/webshell',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/dashboard/node-manage': RouteRecordInfo<
      '/dashboard/node-manage',
      '/dashboard/node-manage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/overview': RouteRecordInfo<
      '/dashboard/overview',
      '/dashboard/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/scripts': RouteRecordInfo<
      '/dashboard/scripts',
      '/dashboard/scripts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/servers': RouteRecordInfo<
      '/dashboard/servers',
      '/dashboard/servers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/servers-detail/[backendId]': RouteRecordInfo<
      '/dashboard/servers-detail/[backendId]',
      '/dashboard/servers-detail/:backendId',
      { backendId: ParamValue<true> },
      { backendId: ParamValue<false> },
      | never
    >,
    '/dashboard/sessions': RouteRecordInfo<
      '/dashboard/sessions',
      '/dashboard/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/settings': RouteRecordInfo<
      '/dashboard/settings',
      '/dashboard/settings',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/settings/general'
      | '/dashboard/settings/login'
      | '/dashboard/settings/notification'
      | '/dashboard/settings/site'
    >,
    '/dashboard/settings/general': RouteRecordInfo<
      '/dashboard/settings/general',
      '/dashboard/settings/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/settings/login': RouteRecordInfo<
      '/dashboard/settings/login',
      '/dashboard/settings/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/settings/notification': RouteRecordInfo<
      '/dashboard/settings/notification',
      '/dashboard/settings/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/settings/site': RouteRecordInfo<
      '/dashboard/settings/site',
      '/dashboard/settings/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/token': RouteRecordInfo<
      '/dashboard/token',
      '/dashboard/token',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tokenCeate': RouteRecordInfo<
      '/dashboard/tokenCeate',
      '/dashboard/tokenCeate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tokenDetail': RouteRecordInfo<
      '/dashboard/tokenDetail',
      '/dashboard/tokenDetail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tokenEdit': RouteRecordInfo<
      '/dashboard/tokenEdit',
      '/dashboard/tokenEdit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tokenImport': RouteRecordInfo<
      '/dashboard/tokenImport',
      '/dashboard/tokenImport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server-detail': RouteRecordInfo<
      '/server-detail',
      '/s/:uuid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
        | '/dashboard/about'
        | '/dashboard/account'
        | '/dashboard/agents'
        | '/dashboard/app'
        | '/dashboard/app-panel'
        | '/dashboard/app-panel/[id]'
        | '/dashboard/app-panel/list'
        | '/dashboard/app/[extensionRoute]'
        | '/dashboard/app/docker'
        | '/dashboard/app/files'
        | '/dashboard/app/firewall'
        | '/dashboard/app/process'
        | '/dashboard/batch-exec'
        | '/dashboard/cost'
        | '/dashboard/cron'
        | '/dashboard/cron-history/[cronName]'
        | '/dashboard/exec'
        | '/dashboard/js-runtime'
        | '/dashboard/kv'
        | '/dashboard/loadbalance'
        | '/dashboard/logs'
        | '/dashboard/map'
        | '/dashboard/node-manage'
        | '/dashboard/node/[uuid]'
        | '/dashboard/node/[uuid]/LatencyView'
        | '/dashboard/node/[uuid]/[extensionRoute]'
        | '/dashboard/node/[uuid]/docker'
        | '/dashboard/node/[uuid]/files'
        | '/dashboard/node/[uuid]/firewall'
        | '/dashboard/node/[uuid]/latency'
        | '/dashboard/node/[uuid]/ping'
        | '/dashboard/node/[uuid]/process'
        | '/dashboard/node/[uuid]/setting'
        | '/dashboard/node/[uuid]/status'
        | '/dashboard/node/[uuid]/traffic'
        | '/dashboard/node/[uuid]/update'
        | '/dashboard/node/[uuid]/webshell'
        | '/dashboard/overview'
        | '/dashboard/scripts'
        | '/dashboard/servers'
        | '/dashboard/servers-detail/[backendId]'
        | '/dashboard/sessions'
        | '/dashboard/settings'
        | '/dashboard/settings/general'
        | '/dashboard/settings/login'
        | '/dashboard/settings/notification'
        | '/dashboard/settings/site'
        | '/dashboard/token'
        | '/dashboard/tokenCeate'
        | '/dashboard/tokenDetail'
        | '/dashboard/tokenEdit'
        | '/dashboard/tokenImport'
      views:
        | 'default'
    }
    'src/pages/dashboard/about.vue': {
      routes:
        | '/dashboard/about'
      views:
        | never
    }
    'src/pages/dashboard/account.vue': {
      routes:
        | '/dashboard/account'
      views:
        | never
    }
    'src/pages/dashboard/agents.vue': {
      routes:
        | '/dashboard/agents'
      views:
        | never
    }
    'src/pages/dashboard/app.vue': {
      routes:
        | '/dashboard/app'
        | '/dashboard/app/[extensionRoute]'
        | '/dashboard/app/docker'
        | '/dashboard/app/files'
        | '/dashboard/app/firewall'
        | '/dashboard/app/process'
      views:
        | 'default'
    }
    'src/pages/dashboard/app/[extensionRoute].vue': {
      routes:
        | '/dashboard/app/[extensionRoute]'
      views:
        | never
    }
    'src/pages/dashboard/app/docker.vue': {
      routes:
        | '/dashboard/app/docker'
      views:
        | never
    }
    'src/pages/dashboard/app/files.vue': {
      routes:
        | '/dashboard/app/files'
      views:
        | never
    }
    'src/pages/dashboard/app/firewall.vue': {
      routes:
        | '/dashboard/app/firewall'
      views:
        | never
    }
    'src/pages/dashboard/app/process.vue': {
      routes:
        | '/dashboard/app/process'
      views:
        | never
    }
    'src/pages/dashboard/app-panel.vue': {
      routes:
        | '/dashboard/app-panel'
        | '/dashboard/app-panel/[id]'
        | '/dashboard/app-panel/list'
      views:
        | 'default'
    }
    'src/pages/dashboard/app-panel/[id].vue': {
      routes:
        | '/dashboard/app-panel/[id]'
      views:
        | never
    }
    'src/pages/dashboard/app-panel/list.vue': {
      routes:
        | '/dashboard/app-panel/list'
      views:
        | never
    }
    'src/pages/dashboard/batch-exec.vue': {
      routes:
        | '/dashboard/batch-exec'
      views:
        | never
    }
    'src/pages/dashboard/cost.vue': {
      routes:
        | '/dashboard/cost'
      views:
        | never
    }
    'src/pages/dashboard/cron.vue': {
      routes:
        | '/dashboard/cron'
      views:
        | never
    }
    'src/pages/dashboard/cron-history/[cronName].vue': {
      routes:
        | '/dashboard/cron-history/[cronName]'
      views:
        | never
    }
    'src/pages/dashboard/exec.vue': {
      routes:
        | '/dashboard/exec'
      views:
        | never
    }
    'src/pages/dashboard/js-runtime.vue': {
      routes:
        | '/dashboard/js-runtime'
      views:
        | never
    }
    'src/pages/dashboard/kv.vue': {
      routes:
        | '/dashboard/kv'
      views:
        | never
    }
    'src/pages/dashboard/loadbalance.vue': {
      routes:
        | '/dashboard/loadbalance'
      views:
        | never
    }
    'src/pages/dashboard/logs.vue': {
      routes:
        | '/dashboard/logs'
      views:
        | never
    }
    'src/pages/dashboard/map.vue': {
      routes:
        | '/dashboard/map'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid].vue': {
      routes:
        | '/dashboard/node/[uuid]'
        | '/dashboard/node/[uuid]/LatencyView'
        | '/dashboard/node/[uuid]/[extensionRoute]'
        | '/dashboard/node/[uuid]/docker'
        | '/dashboard/node/[uuid]/files'
        | '/dashboard/node/[uuid]/firewall'
        | '/dashboard/node/[uuid]/latency'
        | '/dashboard/node/[uuid]/ping'
        | '/dashboard/node/[uuid]/process'
        | '/dashboard/node/[uuid]/setting'
        | '/dashboard/node/[uuid]/status'
        | '/dashboard/node/[uuid]/traffic'
        | '/dashboard/node/[uuid]/update'
        | '/dashboard/node/[uuid]/webshell'
      views:
        | 'default'
    }
    'src/pages/dashboard/node/[uuid]/[extensionRoute].vue': {
      routes:
        | '/dashboard/node/[uuid]/[extensionRoute]'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/docker.vue': {
      routes:
        | '/dashboard/node/[uuid]/docker'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/files.vue': {
      routes:
        | '/dashboard/node/[uuid]/files'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/firewall.vue': {
      routes:
        | '/dashboard/node/[uuid]/firewall'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/latency.vue': {
      routes:
        | '/dashboard/node/[uuid]/latency'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/LatencyView.vue': {
      routes:
        | '/dashboard/node/[uuid]/LatencyView'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/ping.vue': {
      routes:
        | '/dashboard/node/[uuid]/ping'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/process.vue': {
      routes:
        | '/dashboard/node/[uuid]/process'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/setting.vue': {
      routes:
        | '/dashboard/node/[uuid]/setting'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/status.vue': {
      routes:
        | '/dashboard/node/[uuid]/status'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/traffic.vue': {
      routes:
        | '/dashboard/node/[uuid]/traffic'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/update.vue': {
      routes:
        | '/dashboard/node/[uuid]/update'
      views:
        | never
    }
    'src/pages/dashboard/node/[uuid]/webshell.vue': {
      routes:
        | '/dashboard/node/[uuid]/webshell'
      views:
        | never
    }
    'src/pages/dashboard/node-manage.vue': {
      routes:
        | '/dashboard/node-manage'
      views:
        | never
    }
    'src/pages/dashboard/overview.vue': {
      routes:
        | '/dashboard/overview'
      views:
        | never
    }
    'src/pages/dashboard/scripts.vue': {
      routes:
        | '/dashboard/scripts'
      views:
        | never
    }
    'src/pages/dashboard/servers.vue': {
      routes:
        | '/dashboard/servers'
      views:
        | never
    }
    'src/pages/dashboard/servers-detail/[backendId].vue': {
      routes:
        | '/dashboard/servers-detail/[backendId]'
      views:
        | never
    }
    'src/pages/dashboard/sessions.vue': {
      routes:
        | '/dashboard/sessions'
      views:
        | never
    }
    'src/pages/dashboard/settings.vue': {
      routes:
        | '/dashboard/settings'
        | '/dashboard/settings/general'
        | '/dashboard/settings/login'
        | '/dashboard/settings/notification'
        | '/dashboard/settings/site'
      views:
        | 'default'
    }
    'src/pages/dashboard/settings/general.vue': {
      routes:
        | '/dashboard/settings/general'
      views:
        | never
    }
    'src/pages/dashboard/settings/login.vue': {
      routes:
        | '/dashboard/settings/login'
      views:
        | never
    }
    'src/pages/dashboard/settings/notification.vue': {
      routes:
        | '/dashboard/settings/notification'
      views:
        | never
    }
    'src/pages/dashboard/settings/site.vue': {
      routes:
        | '/dashboard/settings/site'
      views:
        | never
    }
    'src/pages/dashboard/token.vue': {
      routes:
        | '/dashboard/token'
      views:
        | never
    }
    'src/pages/dashboard/tokenCeate.vue': {
      routes:
        | '/dashboard/tokenCeate'
      views:
        | never
    }
    'src/pages/dashboard/tokenDetail.vue': {
      routes:
        | '/dashboard/tokenDetail'
      views:
        | never
    }
    'src/pages/dashboard/tokenEdit.vue': {
      routes:
        | '/dashboard/tokenEdit'
      views:
        | never
    }
    'src/pages/dashboard/tokenImport.vue': {
      routes:
        | '/dashboard/tokenImport'
      views:
        | never
    }
    'src/pages/server-detail.vue': {
      routes:
        | '/server-detail'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
